name: release

on:
  push:
    branch:
      - main

jobs:
  check-ip:
    name: check-ip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create dag run
      run: |
        a.sh
