name: release

on:
  release:
    types: [published]

jobs:
  trigger_pipeline:
    name: Trigger pipeline
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Create dag run
      run: |
        sudo apt-get update
        sudo apt-get install ca-certificates
        curl -X POST https://af-dev.sktai.io/api/experimental/dags/sample_gpt_data_pipeline_v2/dag_runs
